import { calcPAYE, calcCIT, calcVAT, calcWHT, calcStampDuty, calcCGT, calcDigitalVAT, calcTakeHome, calcPension, calcNHF, calcDevelopmentLevy } from './src/lib/taxEstimator.js';

const r1 = calcPAYE({ monthlySalary: 416667, pension: false });
console.log('PAYE annual 5M, no relief:', r1.totalTax, 'monthly:', r1.monthlyTax.toFixed(2), 'takeHome:', r1.monthlyTakeHome.toFixed(2));
const r2 = calcPAYE({ monthlySalary: 300000, pension: true, nhf: true, basicSalary: 200000 });
console.log('PAYE annual 3.6M w/reliefs:', r2.totalTax.toFixed(2), 'takeHome:', r2.monthlyTakeHome.toFixed(2));
const c = calcCIT({ annualTurnover: 50000000, fixedAssets: 100000000 });
console.log('CIT small:', c.isSmall, c.totalTax);
const c2 = calcCIT({ annualTurnover: 200000000, fixedAssets: 100000000 });
console.log('CIT large:', c2.isSmall, c2.breakdown.map(b => b.value), c2.totalTax);
const c3 = calcCIT({ annualTurnover: 50000000, fixedAssets: 100000000, isProfessional: true });
console.log('CIT professional 50M (not small):', c3.isSmall, c3.totalTax);
const v = calcVAT({ annualSales: 1000000, annualInputPurchases: 400000 });
console.log('VAT:', v.outputVat, '-', v.inputVat, '=', v.totalTax);
const v2 = calcVAT({ annualSales: 1000000, annualInputPurchases: 2000000 });
console.log('VAT negative (carryover):', v2.totalTax);
const d = calcDigitalVAT({ annualTurnover: 5000000 });
console.log('Digital VAT 5M:', d.totalTax);
const w1 = calcWHT({ paymentType: 'professional', amount: 1000000, hasTin: true });
console.log('WHT 1M w/TIN:', w1.rate, w1.totalTax);
const w2 = calcWHT({ paymentType: 'professional', amount: 5000000, hasTin: false });
console.log('WHT 5M no TIN:', w2.rate, w2.totalTax);
const w3 = calcWHT({ paymentType: 'dividends', amount: 5000000, hasTin: true });
console.log('WHT dividends 5M w/TIN:', w3.rate, w3.totalTax);
const s = calcStampDuty({ instrumentType: 'conveyance', value: 100000000 });
console.log('Stamp conveyance 100M:', s.totalTax);
const s2 = calcStampDuty({ instrumentType: 'conveyance', value: 5000000 });
console.log('Stamp conveyance 5M (exempt):', s.totalTax === 0 ? '0' : s.totalTax, '| note:', s.note);
const g = calcCGT({ gains: 60000000 });
console.log('CGT individual 60M:', g.totalTax);
const g2 = calcCGT({ gains: 100000000, taxpayer: 'company' });
console.log('CGT company 100M:', g2.totalTax);
const tk = calcTakeHome({ monthlySalary: 300000, pension: true, nhf: true, basicSalary: 200000 });
console.log('Take-home:', tk.monthlyTakeHome.toFixed(2), 'employerPension/yr:', tk.employerPension);
const p = calcPension({ monthlySalary: 300000 });
console.log('Pension monthly:', p.monthlyEmployee, p.monthlyEmployer, p.monthlyTotal);
const n = calcNHF({ basicSalary: 200000 });
console.log('NHF:', n.monthly, n.annual);
const dl = calcDevelopmentLevy({ annualProfit: 10000000 });
console.log('Dev levy 10M:', dl.totalTax);